<?php
/**
 *
 * SM Listing Tabs - Version 2.6.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
if ($this->_isAjax()) {
    $products = $this->_ajaxLoad();
    $config = $this->_getConfig();
} else {
    $config = $this->getData('config');
    $products = $this->getData('products');
}
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_config = $this->helper('Sm\Revo\Helper\Data');
$homeStyle = $_config->getThemeLayout('home_style');
$viewMode = 'grid';

$homeStyle = $_config->getThemeLayout('home_style');

if ($homeStyle == 'home-3' || $homeStyle == 'home-4') {
    $image = 'category_page_grid3';
} else {
    $image = 'category_page_grid';
}

$showDescription = false;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

$type_loadmore = $config['type_show'] == 'loadmore' ? true : false;
$cls_mark = $type_loadmore ? ' ltabs-mark ' : '';
if (count($products)) {
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="clearfix <?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div class="products list items product-items item <?php echo $type_loadmore == false ? ' owl-carousel owl-theme ' : ''; ?>" <?php echo $type_loadmore ? 'data-liffect="fadeIn"' : ''; ?>>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php
            $nb_type_show = $config['type_show'];
            $nb_rows = $config['nb_row'];
            $i = 0;
            $count = count($products);
            foreach ($products as $_product): $i++; ?>
                <?php if ($i % $nb_rows == 1 || $nb_rows == 1) { ?>
                    <div class="item ltabs-item product product-item  <?php echo $cls_mark ?>">
                <?php } ?>
                <div class="item-inner" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>

                    <div class="box-image">
                        <a href="<?php /* @escapeNotVerified */
                        echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                    </div>

                    <div class="product details product-item-details box-info">
                        <div class="name-price">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <h2 class="product name product-item-name product-name">
                                <a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */
                                   echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </h2>

                            <?php /* @escapeNotVerified */
                            echo $block->getProductPrice($_product) ?>
                        </div>


                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <div class="bottom-action-w">
                            <div class="bottom-action">
                                <?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                  action="<?= /* @NoEscape */
                                                  $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */
                                                $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */
                                                Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */
                                                $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart btn-action btn-cart">
														<span><?= /* @escapeNotVerified */
                                                            __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available"><span><?= /* @escapeNotVerified */
                                                        __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                        __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php } ?>

                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                    <?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#" class="action towishlist btn-action link-wishlist"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php /* @escapeNotVerified */
                                               echo $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist" role="button">
													<span><?php /* @escapeNotVerified */
                                                        echo __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                    <?php } ?>

                                    <?php if ($_config->getAdvanced('show_compare_button')) { ?>
                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                        <a href="#" class="action tocompare btn-action link-compare"
                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php /* @escapeNotVerified */
                                           echo $compareHelper->getPostDataParams($_product); ?>' role="button">
												<span><?php /* @escapeNotVerified */
                                                    echo __('Add to Compare') ?></span>
                                        </a>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>

                        <?php
                        if ((int)$config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
                            $specialToDate = $_product->getSpecialToDate();
                            ?>
                            <div class="deals-countdown"
                                 data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
                                <div class="deals-time time-day">
                                    <div class="num-time"></div>
                                    <div class="title-time"></div>
                                </div>
                                <div class="deals-time time-hours">
                                    <div class="num-time"></div>
                                    <div class="title-time"></div>
                                </div>
                                <div class="deals-time time-mins">
                                    <div class="num-time"></div>
                                    <div class="title-time"></div>
                                </div>
                                <div class="deals-time time-secs">
                                    <div class="num-time"></div>
                                    <div class="title-time"></div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>

                </div>
                <?php if ($i % $nb_rows == 0 || $i == $count) { ?>
                    </div>
                <?php } ?>
            <?php endforeach; ?>
        </div>
    </div>
    <?php
} else {
    if (!$this->_isAjax()) { ?>
        <div class="message info empty">
            <div><?php /* @escapeNotVerified */
                echo __('We can\'t find products matching the selection.') ?></div>
        </div>
    <?php }
} ?>