<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */

$_config = $this->helper('Sm\Revo\Helper\Data');
$headerStyle = $_config->getThemeLayout('header_style');
$compile_less = $_config->getAdvanced('compile_less');

include($block->getTemplateFile("Magento_Theme::html/header-style/" . $headerStyle . ".phtml"));
if ($compile_less) {
    echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Header")->setTemplate("Magento_Theme::html/compile_less.phtml")->toHtml();
}
?>

<?php if ($_config->getGeneral('menu_ontop') == 1) { ?>
    <?php if ($headerStyle == "header-4") { ?>
        <script type="text/javascript">
            require([
                'jquery'
            ], function ($) {
                $window = $(window);

                menu_offset_top = 70;

                function processScroll() {
                    var scrollTop = $window.scrollTop();
                    if (scrollTop >= menu_offset_top) {
                        $('.header').addClass('menu-on-top');
                        $('body').addClass('body-on-top');
                    } else if (scrollTop <= menu_offset_top) {
                        $('.header').removeClass('menu-on-top');
                        $('body').removeClass('body-on-top');
                    }
                }

                processScroll();
                $window.scroll(function () {
                    processScroll();
                });

            });
        </script>

    <?php } else { ?>

        <script type="text/javascript">
            require([
                'jquery'
            ], function ($) {
                $window = $(window);
                if ($('.header-bottom').length) {
                    menu_offset_top = $('.header-bottom').offset().top;

                    function processScroll() {
                        var scrollTop = $window.scrollTop();
                        if (scrollTop >= menu_offset_top) {
                            $('.header-bottom').addClass('menu-on-top');
                            $('body').addClass('body-on-top');
                        } else if (scrollTop <= menu_offset_top) {
                            $('.header-bottom').removeClass('menu-on-top');
                            $('body').removeClass('body-on-top');
                        }
                    }

                    processScroll();
                    $window.scroll(function () {
                        processScroll();
                    });
                }
            });
        </script>
    <?php } ?>

<?php } ?>
