<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_config = $this->helper('Sm\Revo\Helper\Data');
$count_item = $_productCollection->count();
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_list_100';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $tag_id = "sm_filterproducts_" . time() . rand() . "";
    ?>

    <div class="basic-slider block">
        <div class="title-home block-title">
            <strong><?php echo $this->_getConfig('title_module'); ?></strong>
        </div>

        <div class="basic-slider-content block-content">

            <?php
            if ($this->_getConfig('product_source') == 'countdown_products') {
                $dateTo = $this->_getConfig('date_to', '');
                ?>
                <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($dateTo)); ?>">
                    <div class="deals-time time-day">
                        <div class="num-time"></div>
                        <div class="title-time"></div>
                    </div>
                    <div class="deals-time time-hours">
                        <div class="num-time"></div>
                        <div class="title-time"></div>
                    </div>
                    <div class="deals-time time-mins">
                        <div class="num-time"></div>
                        <div class="title-time"></div>
                    </div>
                    <div class="deals-time time-secs">
                        <div class="num-time"></div>
                        <div class="title-time"></div>
                    </div>
                </div>
            <?php } ?>

            <?php $iterator = 1; ?>
            <div id="<?php echo $tag_id; ?>" class="basic-products-slider owl-carousel owl-theme">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php
                $j = 0;
                $count = 0;
                $nb_rows = $this->_getConfig('nb_rows');
                foreach ($_productCollection as $_product):
                    $count++;
                    $j++;
                    ?>
                    <?php if ($count % $nb_rows == 1 || $nb_rows == 1) { ?>
                    <div class="item">
                <?php } ?>
                    <div class="item-inner">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image 
                        ?>
                        <div class="box-image">
                            <a href="<?= /* @escapeNotVerified */
                            $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                        </div>

                        <div class="box-info">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <h2 class="product name product-item-name product-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */
                                   $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */
                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </h2>

                            <div class="deals-review">
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            </div>

                            <?= /* @escapeNotVerified */
                            $block->getProductPrice($_product) ?>

                            <?= $block->getProductDetailsHtml($_product) ?>

                            <?php
                            if ((int)$this->_getConfig('display_countdown') && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
                                $specialToDate = $_product->getSpecialToDate();
                                ?>
                                <div class="deals-countdown clearfix"
                                     data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
                                    <div class="deals-time time-day">
                                        <div class="num-time"></div>
                                        <div class="title-time"></div>
                                    </div>
                                    <div class="deals-time time-hours">
                                        <div class="num-time"></div>
                                        <div class="title-time"></div>
                                    </div>
                                    <div class="deals-time time-mins">
                                        <div class="num-time"></div>
                                        <div class="title-time"></div>
                                    </div>
                                    <div class="deals-time time-secs">
                                        <div class="num-time"></div>
                                        <div class="title-time"></div>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>

                    <?php if (($count % $nb_rows == 0 || $count == $count_item)) { ?>
                    </div>
                <?php } ?>

                <?php endforeach; ?>
            </div>
        </div>
    </div>


    <script>
        require([
            'jquery'
        ], function ($) {
            var $element = $('#<?php echo $tag_id ?>');

            function CountDown(date, id) {
                dateNow = new Date();
                amount = date.getTime() - dateNow.getTime();
                delete dateNow;
                if (amount < 0) {
                    id.html("Now!");
                } else {
                    days = 0;
                    hours = 0;
                    mins = 0;
                    secs = 0;
                    out = "";
                    amount = Math.floor(amount / 1000);
                    days = Math.floor(amount / 86400);
                    amount = amount % 86400;
                    hours = Math.floor(amount / 3600);
                    amount = amount % 3600;
                    mins = Math.floor(amount / 60);
                    amount = amount % 60;
                    secs = Math.floor(amount);
                    $(".time-day .num-time", id).text(days);
                    $(".time-day .title-time", id).text(((days <= 1) ? "<?php echo __('Day')?>" : "<?php echo __('Days')?>"));
                    $(".time-hours .num-time", id).text(hours);
                    $(".time-hours .title-time", id).text(((hours <= 1) ? "<?php echo __('Hour')?>" : "<?php echo __('Hours')?>"));
                    $(".time-mins .num-time", id).text(mins);
                    $(".time-mins .title-time", id).text(((mins <= 1) ? "<?php echo __('Minute')?>" : "<?php echo __('Minutes')?>"));
                    $(".time-secs .num-time", id).text(secs);
                    $(".time-secs .title-time", id).text(((secs <= 1) ? "<?php echo __('Second')?>" : "<?php echo __('Seconds')?>"));
                    setTimeout(function () {
                        CountDown(date, id)
                    }, 1000);
                }
            }

            $(".deals-countdown", $element).each(function () {
                var timer = $(this).data('timer');
                var data = new Date(timer);
                CountDown(data, $(this));
            });
        });
    </script>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        
        
        
        
        </script>
    <?php endif; ?>
<?php endif; ?>
