<?php
/*------------------------------------------------------------------------
 # SM Super Categories - Version 2.1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$helper = $this->_helper();
if ($this->_isAjax()) {
    $catid = $this->getRequest()->getPost('categoryid');
    $start = (int)$this->getRequest()->getPost('ajax_reslisting_start');
    $list = $this->getListCriterionFilter($catid);
    $child_items = $list[$catid]['child'];
    $tag_id = $this->getRequest()->getPost('super_categories_moduleid');
}

if (!empty($child_items)) {
$j = $this->getRequest()->getPost('ajax_reslisting_start', 0);
$i = 0;
$count = count($child_items);
$limit = $this->_getConfig('product_limitation');
$full = $this->_getConfig('full-container');

$nbi_type_show = $this->_getConfig('nbi_type_show', 'loadmore');
//$nbi_rows = $this->_getConfig('nbi_rows', 1);
$nbi_rows = 3;
// if ($nbi_type_show == 'slider') {
// 	echo '<div class="super-items-inner owl2-carousel spctabs-slider ">';
// }
?>
<?php if ($full == 1) {
    echo '<div class="full-container">';
} ?>
    <div id="cus-slider-super" class="slider-products super-slider">
        <?php
        $c = 0;
        foreach ($child_items as $_product) {
            $c++;
            ?>
            <div class="item">
                <div class="item-inner">
                    <?php if ($_product->_image) { ?>
                        <div class="box-image">
                            <a href="<?php echo $_product->link ?>"
                               title="<?php echo $_product->title; ?>"
                                <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                            >
                                <img src="<?php echo $_product->_image; ?>"
                                     title="<?php echo $_product->title; ?>"
                                     alt="<?php echo $_product->title; ?>">
                            </a>
                            <!--LABEL PRODUCT-->
                            <?php
                            $specialprice = $_product->getSpecialPrice();
                            $specialPriceFromDate = $_product->getSpecialFromDate();
                            $specialPriceToDate = $_product->getSpecialToDate();

                            $today = time();
                            $price = $_product->getPrice();
                            if ($price) {
                                $sale = round((($price - $specialprice) / $price) * 100);
                            }
                            if ($specialprice) {
                                if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
                                    <div class="label-product label-sale">
												<span class="sale-product-icon">
													<?php if ($sale) {
                                                        echo $sale . '%';
                                                    } else {
                                                        echo __('Sale');
                                                    } ?>
												</span>
                                    </div>
                                <?php }
                            }
                            ?>

                            <?php
                            $now = date("Y-m-d");
                            $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
                            $newsTo = substr($_product->getNewsToDate(), 0, 10);

                            if ($newsTo != '' || $newsFrom != '') {
                                if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                    <div class="label-product label-new">
                                        <span class="new-product-icon"><?php echo __('New'); ?></span>
                                    </div>
                                <?php }
                            } ?>
                            <!--END LABEL PRODUCT-->
                        </div>
                    <?php } ?>

                    <!-- Begin spc-content -->
                    <?php ?>
                    <div class="product details product-item-details box-info">
                        <div class="name-price">
                            <?php if ((int)$this->_getConfig('product_title_display', 1)) { ?>
                                <h2 class="product name product-item-name product-name">
                                    <a href="<?php echo $_product->link; ?>" title="<?php echo $_product->title; ?>"
                                        <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                    >
                                        <?php echo $helper->truncate($_product->title, $this->_getConfig('product_title_maxlength')); ?>
                                    </a>
                                </h2>
                            <?php } ?>
                            <?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
                                <?php echo $this->getProductPrice($_product); ?>
                            <?php } ?>
                        </div>


                        <?php if ($this->_getConfig('product_description_display') == 1 && $helper->_trimEncode($_product->_description)) { ?>
                            <div class="spc-description">
                                <?php echo $_product->_description; ?>
                            </div>
                        <?php } ?>

                        <?php if ($this->_getConfig('product_source') != 'media') { ?>
                            <?php if ((int)$this->_getConfig('product_reviews_count', 1)) { ?>
                                <div class="spc-review">
                                    <?php
                                    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
                                    echo $block->getReviewsSummaryHtml($_product, $templateType);
                                    ?>
                                </div>
                            <?php } ?>

                        <?php } ?>

                        <?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
                            <div class="spc-detail">
                                <a href="<?php echo $_product->link ?>"
                                   title="<?php echo $_product->title; ?>"
                                    <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                >
                                    <?php echo $this->_getConfig('product_readmore_text', 'Details'); ?>
                                </a>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>

            <?php
            if ($c == 4) break;
        }
        ?>
    </div>
<div id="cus-list-super" class="list-products">
    <?php
    $c = 0;
    $cc = 0;
    foreach ($child_items as $_product) {
        if ($c >= 0 && $c <= 3) {
            $c++;
            continue;
        }
        $cc++;
        ?>
        <?php if ($cc % $nbi_rows == 1 || $nbi_rows == 1) { ?>
            <div class="item item-<?php echo $cc; ?>">
        <?php } ?>
        <div class="item-inner">
            <?php if ($_product->_image) { ?>
                <div class="box-image">
                    <a href="<?php echo $_product->link ?>"
                       title="<?php echo $_product->title; ?>"
                        <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                    >
                        <img src="<?php echo $_product->_image; ?>"
                             title="<?php echo $_product->title; ?>"
                             alt="<?php echo $_product->title; ?>">
                    </a>
                    <!--LABEL PRODUCT-->
                    <?php /*
							$specialprice = $_product->getSpecialPrice();
							$specialPriceFromDate = $_product->getSpecialFromDate();
							$specialPriceToDate = $_product->getSpecialToDate();
							
							$today = time();
							$price = $_product->getPrice();
							if($price){
								$sale = round((($price-$specialprice)/$price)*100);
							}
							if ($specialprice) {
								if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
									<div class="label-product label-sale">
										<span class="sale-product-icon">
											<?php if($sale) { echo $sale.'%'; } else {echo __('Sale');} ?>
										</span>
									</div>
								<?php }
							}
						?>
						
						<?php
						$now = date("Y-m-d");
						$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
						$newsTo = substr($_product->getNewsToDate(), 0, 10);
						
						if ($newsTo != '' || $newsFrom != '') {
							if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
									<div class="label-product label-new">
										<span class="new-product-icon"><?php echo __('New'); ?></span>
									</div>
							<?php }
						} */ ?>
                    <!--END LABEL PRODUCT-->
                </div>
            <?php } ?>

            <!-- Begin spc-content -->
            <?php ?>
            <div class="product details product-item-details box-info">
                <div class="name-price">
                    <?php if ((int)$this->_getConfig('product_title_display', 1)) { ?>
                        <h2 class="product name product-item-name product-name">
                            <a href="<?php echo $_product->link; ?>" title="<?php echo $_product->title; ?>"
                                <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                            >
                                <?php echo $helper->truncate($_product->title, $this->_getConfig('product_title_maxlength')); ?>
                            </a>
                        </h2>
                    <?php } ?>
                    <?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
                        <?php echo $this->getProductPrice($_product); ?>
                    <?php } ?>
                </div>


                <?php if ($this->_getConfig('product_description_display') == 1 && $helper->_trimEncode($_product->_description)) { ?>
                    <div class="spc-description">
                        <?php echo $_product->_description; ?>
                    </div>
                <?php } ?>

                <?php if ($this->_getConfig('product_source') != 'media') { ?>
                    <?php if ((int)$this->_getConfig('product_reviews_count', 1)) { ?>
                        <div class="spc-review">
                            <?php
                            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
                            echo $block->getReviewsSummaryHtml($_product, $templateType);
                            ?>
                        </div>
                    <?php } ?>

                <?php } ?>

                <?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
                    <div class="spc-detail">
                        <a href="<?php echo $_product->link ?>"
                           title="<?php echo $_product->title; ?>"
                            <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                        >
                            <?php echo $this->_getConfig('product_readmore_text', 'Details'); ?>
                        </a>
                    </div>
                <?php } ?>
            </div>
        </div>
        <?php if (($cc % $nbi_rows == 0 || $cc == $count)) { ?>
            </div>
        <?php } ?>
        <?php
        $c++;
        if ($c == $limit || $c == $count) break;
    } ?>

    <?php } ?>
</div>
<?php if ($full == 1) {
    echo '</div>';
} ?>

<?php if ($nbi_type_show == 'slider') { ?>
    <script type="text/javascript">
        require([
            'jquery',
            'owlcarousel'
        ], function ($) {
            var $tag_id = $('#<?php echo $tag_id; ?>'),
                parent_active = $('.spctabs-items-selected', $tag_id),
                total_product = parent_active.data('total'),
                tab_active = $('.super-items-inner', parent_active),
                nb_column1 = <?php echo $this->_getConfig('nbi_column1'); ?>,
                nb_column2 = <?php echo $this->_getConfig('nbi_column2'); ?>,
                nb_column3 = <?php echo $this->_getConfig('nbi_column3'); ?>,
                nb_column4 = <?php echo $this->_getConfig('nbi_column4'); ?>;

            tab_active.owlCarousel({
                nav: <?php echo $this->_getConfig('product_nav'); ?>,
                dots: false,
                margin: 30,
                loop:  <?php echo $this->_getConfig('product_loop'); ?>,
                autoplay: <?php echo $this->_getConfig('product_autoplay'); ?>,
                autoplayHoverPause: <?php echo $this->_getConfig('product_autoplayHoverPause'); ?>,
                autoplayTimeout: <?php echo $this->_getConfig('product_intervalTimeout'); ?>,
                autoplaySpeed: <?php echo $this->_getConfig('product_autoplaySpeed'); ?>,
                navSpeed: <?php echo $this->_getConfig('product_navSpeed'); ?>,
                mouseDrag: <?php echo $this->_getConfig('product_mouseDrag'); ?>,
                touchDrag: <?php echo $this->_getConfig('product_touchDrag'); ?>,
                navRewind: true,
                navText: ['', ''],
                responsive: {
                    0: {
                        items: nb_column4,
                        nav: total_product <= nb_column4 ? false : ((<?php echo $this->_getConfig('product_nav'); ?>) ? true : false)
                    },
                    480: {
                        items: nb_column3,
                        nav: total_product <= nb_column3 ? false : ((<?php echo $this->_getConfig('product_nav'); ?>) ? true : false)
                    },
                    768: {
                        items: nb_column2,
                        nav: total_product <= nb_column2 ? false : ((<?php echo $this->_getConfig('product_nav'); ?>) ? true : false)
                    },
                    1200: {
                        items: nb_column1,
                        nav: total_product <= nb_column1 ? false : ((<?php echo $this->_getConfig('product_nav'); ?>) ? true : false)
                    }
                }
            });

        });
    </script>
<?php } ?>

<script type="text/javascript">
    require([
        'jquery',
        'owlcarousel',
        'domReady!'
    ], function ($, owlCarousel) {
        $(document).ready(function () {
            var cus_slider_super = $(".sm-super-categories .super-slider");

            cus_slider_super.owlCarousel({
                responsive: {
                    0: {
                        items: 1
                    },
                    480: {
                        items: 1
                    },
                    768: {
                        items: 1
                    },
                    991: {
                        items: 1
                    },
                    1200: {
                        items: 1
                    }
                },
                autoplay: false,
                loop: true,
                nav: false, // Show next and prev buttons
                dots: true,
                autoplaySpeed: 500,
                navSpeed: 500,
                dotsSpeed: 500,
                autoplayHoverPause: true,
                margin: 0,
            });
        });
    });

</script>

