<?php
$collection=$this->getDulieu();
$card=$this->getCard();
?>
<table class="table table-hover">
    <thead>
    <tr>
        <th>Date</th>
        <th>Code</th>
        <th>Amount</th>
        <th>action</th>
    </tr>
    </thead>
    <?php foreach ($collection as $value) : ?>
    <tbody>
    <tr>
        <td><?php echo $value['action_time']?></td>
        <td><?php echo $value['code']?></td>
        <td><?php echo $value['amount']?></td>
        <td><?php echo $value['action']?></td>
    </tr>
    </tbody>
    <?php endforeach ?>
</table>























