<?php
/*------------------------------------------------------------------------
# SM Instagram Gallery - Version 2.0.1
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$helper = $this->_helper();
//$tag_id = 'sm_instagram_gallery_1';
$tag_id = 'sm_instagram_gallery_' . time() . rand();
?>
<?php if ($this->_getConfig('display_title', 1)) { ?>
    <?php if ($this->_getConfig('title')) { ?>
        <div class="twitter_title_text">
            <?php echo $this->_getConfig('title', 'Sm Instagram Gallery'); ?>
        </div>
    <?php } ?>
<?php } ?>

<?php if ($this->_getConfig('pretext') != null) { ?>
    <div class="bs-pretext">
        <?php echo $this->_getConfig('pretext'); ?>
    </div>
<?php } ?>

<div id="<?php echo $tag_id; ?>" class="sm-instagram-gallery">
    <div class="instagram-wrap">
        <!-- End Tabs-->
        <div class="instagram-title">
            <span><?php echo __('#revofurniture'); ?></span>
        </div>
        <div class="instagram-items-container"><!--Begin Items-->
            <?php
            echo $this->getLayout()->createBlock("Sm\InstagramGallery\Block\InstagramGallery")->setTemplate("Sm_InstagramGallery::default_items_id5.phtml")->toHtml();
            ?>
        </div>
        <!--End Items-->

        <div class="viewall">
            <a href="#"><?php echo __('View all'); ?></a>
        </div>
    </div>
</div><!-- End Sm-twitter-products -->
<?php if ($this->_getConfig('posttext') != null) { ?>
    <div class="bs-posttext">
        <?php echo $this->_getConfig('posttext'); ?>
    </div>
<?php } ?>
