<div class="header-container header-style-3">
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-4 col-sm-6 col-xs-12 customer-action-header">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top-info-header')->toHtml(); ?>
                </div>

                <div class="col-lg-7 col-md-8 col-sm-6 col-xs-12 header-top-links">
                    <div class="inner">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('call-us-header')->toHtml(); ?>

                        <div class="dropdown-block block-login">
                            <?php
                            $login_customer = $block->getLayout()->createBlock('Magento\Customer\Block\Account\Customer');
                            ?>

                            <?php if ($login_customer->customerLoggedIn()) { ?>
                                <a class="cus-btn" href="<?php echo $block->getUrl('customer/account/logout') ?>"
                                   title="<?php echo __('Logout'); ?>">
                                    <i class="fa fa-unlock-alt"></i>
                                    <?php echo __('Logout'); ?>
                                </a>
                            <?php } else { ?>
                                <a class="cus-btn" href="<?php echo $block->getUrl('customer/account/login') ?>"
                                   title="<?php echo __('Login') ?>">
                                    <i class="fa fa-lock"></i>
                                    <?php echo __('Login') ?>
                                </a>
                            <?php }
                            ?>
                        </div>
                        <div class="dropdown-block block-myacount">
                            <div class="account-links">
                                <div class="dropdown-toggle">
                                    <a class="myaccount-link" href="javascript:void(0);"
                                       title="<?php echo __('My Account'); ?>"><i
                                                class="fa fa-user"></i><?php echo __('My Account'); ?></a>
                                </div>
                                <ul class="dropdown-list">
                                    <li class="mn-my-account"><a
                                                href="<?php echo $block->getUrl('customer/account'); ?>"
                                                title="<?php echo __('My Account'); ?>"><?php echo __('My Account'); ?></a>
                                    </li>
                                    <li class="mn-my-wishlist"><a href="<?php echo $block->getUrl('wishlist') ?>"
                                                                  title="<?php echo __('My Wish List'); ?>"><?php echo __('My Wish List'); ?></a>
                                    </li>
                                    <li class="mn-top-link-compare"><a
                                                href="<?php echo $block->getUrl('catalog/product_compare/index/') ?>"
                                                title="<?php echo __('My Compare'); ?>"><?php echo __('My Compare'); ?></a>
                                    </li>
                                    <li class="mn-top-link-checkout"><a href="<?php echo $block->getUrl('checkout') ?>"
                                                                        title="<?php echo __('Checkout'); ?>"><?php echo __('Checkout'); ?></a>
                                    </li>
                                    <?php if ($login_customer->customerLoggedIn()) { ?>
                                        <li class="mn-logout"><a
                                                    href="<?php echo $block->getUrl('customer/account/logout') ?>"
                                                    title="<?php echo __('Logout'); ?>">
                                                <?php echo __('Logout'); ?>
                                            </a></li>
                                    <?php } else { ?>
                                        <li class="mn-login"><a
                                                    href="<?php echo $block->getUrl('customer/account/login') ?>"
                                                    title="<?php echo __('Login') ?>">
                                                <?php echo __('Login') ?>
                                            </a></li>
                                    <?php }
                                    ?>

                                </ul>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-middle">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-7 header-middle1">
                    <?php echo $block->getChildHtml('language-header'); ?>
                    <?php echo $block->getChildHtml('currency-header'); ?>
                </div>

                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 header-middle2">
                    <?php echo $block->getChildHtml('logo-header'); ?>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 header-middle3">
                    <div class="minicart-header">
                        <div class="minicart-content">
                            <?php echo $block->getChildHtml('cart-header'); ?>
                        </div>
                    </div>
                    <!-- WISHLIST -->
                    <div class="head-btn header-wishlist">
                        <a class="fa fa-heart-o" href="<?php echo $block->getUrl('wishlist') ?>"></a>
                    </div>

                </div>

            </div>
        </div>
    </div>

    <div class="header-bottom">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 main-megamenu-search">
                    <div class="content-header-bottom">
                        <div class="main-menu">
                            <div class="menu-content">
                                <?php
                                if ($_config->getGeneral('menu_style') == 'megamenu') {
                                    echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
                                } else {
                                    echo $block->getChildHtml('navigation-header');
                                }
                                ?>
                            </div>
                            <div class="navigation-mobile-container">
                                <?php echo $block->getChildHtml('navigation.mobile'); ?>
                            </div>

                        </div>

                        <div class="search-w">
                            <div class="search-button">
                                <span><?php echo __('Search'); ?></span><i class="fa fa-search"></i>
                            </div>
                            <?php echo $block->getChildHtml('search-header'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
