<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block-subscribe-home">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('id5-newsletter-info')->toHtml(); ?>
    <form class="form subscribe"
          novalidate
          action="<?php /* @escapeNotVerified */
          echo $block->getFormActionUrl() ?>"
          method="post"
          data-mage-init='{"validation": {"errorClass": "mage-error"}}'
          id="newsletter-validate-detail">

        <div class="input-box">
            <input class="input-text" name="email" type="email" id="newsletter-footer"
                   placeholder="<?php /* @escapeNotVerified */
                   echo __('Enter your email address') ?>"
                   data-validate="{required:true, 'validate-email':true}"/>
        </div>

        <button class="action subscribe primary" title="<?php /* @escapeNotVerified */
        echo __('Subscribe') ?>" type="submit">
			<span><?php /* @escapeNotVerified */
                echo __('Submit') ?></span>
        </button>
    </form>
</div>
