<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$_config = $this->helper('Sm\Revo\Helper\Data');
?>

<div class="footer-container footer-style-7">
    <div class="footer-content">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="f-top1 col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer7-contactus')->toHtml(); ?>
                    </div>
                    <div class="f-top2 col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <?php echo $block->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('subscribe-home7.phtml')->toHtml(); ?>
                    </div>
                    <div class="f-top3 col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::html/social.phtml')->toHtml(); ?>
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer7-apps')->toHtml(); ?>
                    </div>
                </div>

            </div>
        </div>
        <div class="footer-middle">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="spotlight spotlight1">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('spotlight1')->toHtml(); ?>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="spotlight spotlight2">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('spotlight2')->toHtml(); ?>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="spotlight spotlight3">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('spotlight3')->toHtml(); ?>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="spotlight spotlight4">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('spotlight4')->toHtml(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="copyright-footer">
                <?php if ($_config->getAdvanced('custom_copyright')) { ?>
                    <address><?php echo $_config->getAdvanced('copyright_content') ?></address>
                <?php } else { ?>
                    <address><?php /* @escapeNotVerified */
                        echo $block->getCopyright() ?></address>
                <?php } ?>
            </div>

            <div class="footer-payment">
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
            </div>

        </div>
    </div>


    <?php if ($_config->getAdvanced('show_gototop')) { ?>
        <a id="yt-totop" href="javascript:void(0)" title="Go to Top"></a>

        <script type="text/javascript">
            require([
                'jquery'
            ], function ($) {
                $("#yt-totop").hide();
                $(function () {
                    var wh = $(window).height();
                    var whtml = $(document).height();
                    $(window).scroll(function () {
                        if ($(this).scrollTop() > whtml / 10) {
                            $('#yt-totop').fadeIn();
                        } else {
                            $('#yt-totop').fadeOut();
                        }
                    });
                    $('#yt-totop').click(function () {
                        $('body,html').animate({
                            scrollTop: 0
                        }, 800);
                        return false;
                    });
                });
            });
        </script>
    <?php } ?>

</div>




